version: "2"
services:
  app:
    container_name: server
    restart: always
    privileged: true
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    
      
  mongo:
    container_name: mongo
    image: andresvidal/rpi3-mongodb3
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
 
  rfid:
    container_name: rfid
    image: dragomiralin/pyrfid:v4
    privileged: true
    restart: always
    links:
      - mongo
 
