swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger SHome"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "192.168.56.1"
basePath: "/v2"

schemes:
- "http"


paths:
  /rooms/{dataId}:
    get:
      tags:
      - "sensor"
      summary: "GET data sensor"
      description: ""
      operationId: "dataId"
      produces:
      - "application/json"
      parameters:
      - name: "dataId"
        in: "path"
        description: "ID of data that needs to be fetched"
        required: true
        type: "number"
        format: "number"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/room"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
          
          
          
          
  /rooms/1/ON:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
        
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
  
  
  /rooms/1/OFF:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
         
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
  /rooms/2/ON:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
         
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
  
  /rooms/2/OFF:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
          
  /rooms/3/ON:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
          
  /rooms/3/OFF:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
  
 
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: ""
    flow: "implicit"
    scopes:
      write: ""
      read: ""
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  room:
    type: "object"
    properties:
      camera:
        type: "number"
        format: "number"
      temperatura:
        type: "number"
        format: "number"
      umiditatea:
        type: "number"
        format: "number"
      nivelGaz:
        type: "string"
        format: "string"
      shipDate:
        type: "string"
        format: "date-time"
   
      

 

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
