swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger SHome"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "192.168.56.1"
basePath: "/v2"

schemes:
- "http"


paths:
  /products/{dataId}:
    get:
      tags:
      - "sensor"
      summary: "GET data sensor"
      description: ""
      operationId: "dataId"
      produces:
      - "application/json"
      parameters:
      - name: "dataId"
        in: "path"
        description: "ID of data that needs to be fetched"
        required: true
        type: "number"
        format: "number"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/product"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
          
          
          
          
  /products/LED=ON:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      operationId: "ON"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/switchON"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
  
  
  /products/LED=OFF:
    get:
      tags:
      - "switch"
      summary: "GET switch lights"
      description: ""
      operationId: "OFF"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/switchOFF"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Document not found"
 
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  product:
    type: "object"
    properties:
      camera:
        type: "number"
        format: "number"
      temperatura:
        type: "number"
        format: "number"
      umiditatea:
        type: "number"
        format: "number"
      nivelGaz:
        type: "string"
        format: "string"
      shipDate:
        type: "string"
        format: "date-time"
   
      
  switchON:
    type: "object"
    properties:
      ON:
        type: "string"
        
  switchOFF:
    type: "object"
    properties:
      OFF:
        type: "string"
   
 

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"